"""v3_phase4_inventory_reports

Revision ID: ad7df8209648
Revises: v3_phase3_approvals
Create Date: 2026-02-17 13:21:25.714014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7df8209648'
down_revision = 'v3_phase3_approvals'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_article_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('normalized_input', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_article_id', sa.Integer(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Partial unique index for hard dedup of OPEN reports
    op.create_index(
        'ix_unq_active_missing_reports', 
        'missing_article_reports', 
        ['normalized_input', 'location_id'], 
        unique=True, 
        postgresql_where=sa.text("status = 'OPEN'")
    )

    with op.batch_alter_table('missing_article_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missing_article_reports_normalized_input'), ['normalized_input'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missing_article_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missing_article_reports_normalized_input'))

    op.drop_index('ix_unq_active_missing_reports', table_name='missing_article_reports')
    op.drop_table('missing_article_reports')
    # ### end Alembic commands ###
