"""add_order_number_and_indexes

Revision ID: c8f64cf6440c
Revises: add_draft_groups
Create Date: 2026-02-07 14:39:16.429409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f64cf6440c'
down_revision = 'add_draft_groups'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_transactions_order_number', ['order_number'], unique=False)
        batch_op.create_index('ix_transactions_type_created', ['tx_type', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_type_created')
        batch_op.drop_index('ix_transactions_order_number')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
